version: '3.4'

services:
  rest-geoip:
    #image: twistedneil/eleven:main
    build:
      context: .
    ports:
      - 1323:1323
    volumes:
      - ./db:/opt/
    env_file:
      # create this file
      - .env.compose.production
