version: '3.4'

services:
  rest-geoip:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - MAXMIND_LICENSE=${MAXMIND_LICENSE}
      - MAXMIND_DB_LOCATION=/opt/
      - MAXMIND_DB=GeoLite2-City.mmdb
      - LOGGING=${LOGGING}
      - WEB=${WEB}
      - LISTEN_ADDRESS=${LISTEN_ADDRESS}
      - LISTEN_PORT=${LISTEN_PORT}
