version: '3.4'

services:
  rest-geoip:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - MAXMIND_LICENSE=${MAXMIND_LICENSE}
      - MAXMIND_DB_LOCATION=/opt/
      - MAXMIND_DB=GeoLite2-City.mmdb
