version: '3.4'

services:
  rest-geoip:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./db:/opt/
    environment:
      - API_KEY=${API_KEY}
      - MAXMIND_LICENSE=${MAXMIND_LICENSE}
      - MAXMIND_DB_LOCATION=/opt/
      - MAXMIND_DB=GeoLite2-City.mmdb
      - LOGGING=${LOGGING}
      - WEB=${WEB}
      - LISTEN_ADDRESS=${LISTEN_ADDRESS}
      - LISTEN_PORT=${LISTEN_PORT}
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
      - GIN_MODE=${GIN_MODE}
