name: go-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run Gosec
      run: |
        go get github.com/securego/gosec/cmd/gosec
        $GOPATH/bin/gosec ./...
      env:
        GOPATH: /home/runner/work/TwistTheNeil/go

    - name: Build
      run: |
        bash init_deps.sh
        go get github.com/markbates/pkger/cmd/pkger && $GOPATH/bin/pkger
        $GOPATH/bin/pkger
        go build -v ./...
      env:
        GOPATH: /home/runner/work/TwistTheNeil/go


