name: gosec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code to a GOPATH compatible directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/TwistTheNeil/rest-geoip

    - name: Run Gosec
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}
        cd go/src/github.com/TwistTheNeil/rest-geoip
        go get github.com/securego/gosec/cmd/gosec
        $GOPATH/bin/gosec ./...
      env:
        GOPATH: /home/runner/work/TwistTheNeil/go

